// EJERCICIOS ARRAYS
// CUANDO MUESTRE LOS RESULTADOS POR CONSOLA DEBE APARECER AL PRINCIPIO EL TEXTO 'EJERCICIO NUM --> '
// EN TODOS LOS EJERCICIOS DEBE MOSTRAR EL RESULTADO POR CONSOLA

// 1. CREE UN ARRAY VACIO Y COMPRUEBE SU LONGITUD

// 2. CREE UN ARRAY CON UN UNICO ELEMENTO

// 3. CREE UN ARRAY UN ARRAY MIXTO Y MUESTRE SU CONTENIDO COMO UNA CADENA DE CARACTERES SEPARADAS POR COMAS 

// 4. CREE UN ARRAY CUYOS ELEMENTOS SEAN LOS ARRAYS CREADOS ANTERIORMENTE Y MUESTRE SU CONTENIDO Y LONGITUD 

// 5. DADO EL SIGUIENTE ARRAY, UTILIZANDO LA PROPIEDAD LENGTH, MUESTRE EL ULTIMO ELEMENTO
const CARS = ["Saab", "Volvo", "BMW"];

// 6. EN EL ARRAY ANTERIOR, AÑADA UN ELEMENTO AL FINAL, OTRO AL PRINCIO, MUESTRE EL RESULTADO Y LA LONGITUD DEL ARRAY

// 7. A PARTIR DE LOS ARRAYS DE LOS EJERCICIOS 2 Y 3, CREE UN NUEVO ARRAY

// 8. EN EL ARRAY RESULTANTE DEL EJERCICIO ANTERIOR, ELIMINE EL PRIMER Y ULTIMO ELEMENTO, MUESTRE EL RESULTADO, ADEMAS DEBE APARACER SU LONGITUD

// 9. A PARTIR DE LA SIGUIENTE CADENA DE TEXTO 'CURSO XLIV' CREE UN ARRAY QUE CONTENGA SOLAMENTE COMO ELEMENTOS LOS CARACTERES DE LAS LETRAS


// 10. EN EL ARRAY ANTERIOR, INSERTE COMO ELEMENTOS DE DICHO ARRAY LOS CARACTERES DE LA PALABRA 'DIM' (para que estén detrás del caracter O de CURSO y antes del
// caracter X de XLIV). 

// 11. CREE UN ARRAY A PARTIR DE LA SIGUIENTE CADENA DE TEXTO 'Hoyo de Manzanares, 15 de abril de 2023', DE TAL MANERA QUE LOS ELEMENTOS SEAN
// LA CIUDAD, EL DIA, EL MES Y EL AÑO

// 12. UTILIZANDO UN METODO DE BUSQUEDA, EN EL ARRAY ANTERIOR, MUESTRE LA POSICION QUE OCUPA EL ELEMENTO 15

// 13. ORDENE DE FORMA DESCENDENTE EL SIGUIENTE ARRAY
const array = ["Alberto", "Ana", "Mauricio", "Bernardo", "Zoe"];

// 14. ORDENE EL SIGUIENTE ARRAY
const array1 = [1, 30, 4, 21, 100000];



// UTILIZANDO FUNCIONES DE ARRAYS:
// 15. RECORRA EL ARRAY Y SUMELE 1 A CADA ELEMENTO
const array2 = [5, 10, 15, 20, 25];

// 16. COMPRUEBE SI TODOS LOS ELEMENTOS DEL ARRAY ANTERIOR SON IMPARES

// 17. COMPRUE SI AL MENOS EXISTE UN ELEMENTO DEL ARRAY DEL EJERCICIO 16 QUE SEA PAR

// 18. A PARTIR DEL ARRAY DEL EJERCICIO 15, CREE UN NUEVO ARRAY QUE CONTENGA SOLO LOS NUMEROS IMPARES

// 19. A PARTIR DEL ARRAY DEL EJERCICIO 15, CREE UN NUEVO ARRAY QUE CONTENGA COMO ELEMENTOS, EL RESULTADO DE REALIZAR LA RAIZ CUADRADA A CADA ELEMENTO

// 20. TOMANDO COMO REFERENCIA EL ARRAY DEL EJERCICIO 15, MUESTRE POR PANTALLA LA SUMA DE TODOS SUS ELEMENTOS


// 21. DADO EL SIGUIENTE ARRAY, CREE UNA COPIA SUPERFICIAL Y COMPRUEBE QUE LO HA REALIZADO CORRECTAMENTE
const EQUIPOS = ['R. MADRID', 'R. BETIS', 'ATH BILBAO', 'ATH MADRID'];



